### ISSUE TITLE
Add error check to `os.Remove` calls

### ISSUE THREAD

**Issue by utkuufuk** [paddlesteamer/cloudstash#85]
The following calls to `os.Remove()` are not being checked for errors:
* https://github.com/paddlesteamer/cloudstash/blob/033e404c2a2ddefd320e1d660f6bc7e32d33692d/cmd/cloudstash/main.go#L125
* https://github.com/paddlesteamer/cloudstash/blob/033e404c2a2ddefd320e1d660f6bc7e32d33692d/cmd/cloudstash/main.go#L134
* https://github.com/paddlesteamer/cloudstash/blob/033e404c2a2ddefd320e1d660f6bc7e32d33692d/cmd/cloudstash/main.go#L140
* https://github.com/paddlesteamer/cloudstash/blob/033e404c2a2ddefd320e1d660f6bc7e32d33692d/cmd/cloudstash/main.go#L176
* https://github.com/paddlesteamer/cloudstash/blob/033e404c2a2ddefd320e1d660f6bc7e32d33692d/cmd/cloudstash/main.go#L182

**Comment by paddlesteamer** [comment]
Maybe we can check and log them as warnings.

**Comment by utkuufuk** [comment]
@paddlesteamer Agreed, it doesn't seem like there's something we can do to handle it.
